### ISSUE TITLE
Pod stuck on creating when using fsGroup

### ISSUE THREAD

**Issue by cwrau** [juliohm1978/kubernetes-cifs-volumedriver#18]
Thanks for this awesome project!

Sadly I'm having trouble using the fsGroup feature.
When I use it in my deployments, the pods get stuck in `ContainerCreating` because of `Unable to attach or mount volumes: unmounted volumes=[config], unattached volumes=[config tmp runtime data]: timed out waiting for the condition`.

As soon as I remove the fsGroup, everything works as expected 👌

Have you encountered this before?

**Comment by juliohm1978** [comment]
Hi. Thanks for the report.

Can you enable driver logs? Instructions right at the bottom of the README.md file.

```
## On the Kubernetes node where the Pod is scheduled
touch /var/log/kubernetes-cifs-volumedriver.log
tail -F /var/log/kubernetes-cifs-volumedriver.log
```

Please, note that passwords may show up in this log file. Review before pasting the content here.

**Comment by cwrau** [comment]
Sure:

(This is another pod than the one before)

```log
2020/01/23 09:49:00 [mount -t cifs -o uid=1000,gid=1000,rw,sec=none,cache=none,actimeo=0 //192.168.128.117/pvcs/pvc-736cad20-fbf2-4284-986e-ca35836f5592 /var/lib/kubelet/pods/b445d90a-4081-4c93-bc7e-c89decfea18b/volumes/juliohm~cifs/pvc-736cad20-fbf2-4284-986e-ca35836f5592]
2020/01/23 09:49:00 {"Status":"Success","Message":"","Capabilities":{"Attach":false,"Detach":false}}
```

The mount is really there and works, but the pod is still in `ContainerCreating`

**Comment by halkeye** [comment]
Do you have the same issue if you manually add the uid and his to the mount options instead of using fsgroups? I'm not the author but I wonder if fsgroups does more stuff in k8s

**Comment by cwrau** [comment]
You're right, when I add the `uid`/`gid` via the `opts` it works as it should 🤔

Maybe the `fsgroup` does some kind of check?

**Comment by juliohm1978** [comment]
Hi @cwrau,

I was able to create a similar behaviour using the official nginx image. For this particular case, if I also change the securityContext `runAsUser` and `runAsGroup`, the container fails to start and gets stuck at `ContainerCreating`.

Can you check kubelet logs? For Ubuntu, in the node where the pod is scheduled, you can use

```shell
journalctl -f -u kubelet
```

This might show you why the container is not starting. In the case of nginx, I can see this error message mixed with within the lines:

```
failed to "StartContainer" for "nginx" with CrashLoopBackOff
```

**Comment by cwrau** [comment]
`CrashLoopBackoff` happened to me too, with the nginx pod, that's because it can't start as non root 😄

Gotta change the `command` to `sleep 999999` 😄



Now I can't reproduce it 😭

**Comment by juliohm1978** [comment]
I'm guessing right now that your container is unable to start with the uid you provide. If you can publish a reproducible test case, I'll be able to take a closer look at it.

**Comment by cwrau** [comment]
No, that's not it, we didn't use those flags.

But, I can't reproduce this anymore 😅
It just started working...

Maybe it was a problem with our nodes? 😕

I think I'll just close this, and if it happens again, I'll reopen it 😅

**Comment by juliohm1978** [comment]
Thank you for the feedback! Feel free to open new issues later.
