### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by ballerabdude** [juliohm1978/kubernetes-cifs-volumedriver#20]
Can you add a license?

**Comment by juliohm1978** [comment]
Yes, definitely. I'll catch up on reading about them and get on it. Any suggestions?

**Comment by halkeye** [comment]
https://tldrlegal.com/license/mit-license is my go to, allows anyone to use it, commercial or not, but i can't be held liable.

The other "Do whatever you want" license is https://tldrlegal.com/license/apache-license-2.0-(apache-2.0) but i stick with MIT most of the time, for no real reason

**Comment by juliohm1978** [comment]
MIT sounds fine. Thanks for the suggestion. I never thought it would reach that level of usage :)

Fixed with https://github.com/juliohm1978/kubernetes-cifs-volumedriver/commit/ad497cd04b8ecb0ed9c260eacfc45bbd25438bb0
