### ISSUE TITLE
Mount error using v2.0

### ISSUE THREAD

**Issue by Leopol35** [juliohm1978/kubernetes-cifs-volumedriver#21]
Hello,

First, thanks for your amazing job. I try to deply your plugin using 2.0 on my 1.17.4 cluster.

I use daemontset deployment.

I create a aecret for pv, pv, a pvc and a deployment using the pvc.

Logs of my deployment:

_root@******:/tmp/test-cifs# kubectl describe pods nginx-deployment-b45979dcd-xdsp2
Name:           nginx-deployment-b45979dcd-xdsp2
Namespace:      default
Priority:       0
Node:           ******.domain.fr/10.10.0.39
Start Time:     Fri, 03 Apr 2020 16:20:17 +0200
Labels:         app=nginx
                pod-template-hash=b45979dcd
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/nginx-deployment-b45979dcd
Containers:
  nginx:
    Container ID:
    Image:          nginx
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /dados from test (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lm9nf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  test:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  test-claim
    ReadOnly:   false
  default-token-lm9nf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lm9nf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                  From                          Message
  ----     ------            ----                 ----                          -------
  Warning  FailedScheduling  24m (x2 over 24m)    default-scheduler             error while running "VolumeBinding" filter plugin for pod "nginx-deployment-b45979dcd-xdsp2": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         24m                  default-scheduler             Successfully assigned default/nginx-deployment-b45979dcd-xdsp2 to ******.domain.fr
  Warning  FailedMount       3m48s (x2 over 12m)  kubelet, ******.domain.fr  Unable to attach or mount volumes: unmounted volumes=[test], unattached volumes=[default-token-lm9nf test]: timed out waiting for the condition
  Warning  FailedMount       94s (x19 over 24m)   kubelet, ******.domain.fr  MountVolume.SetUp failed for volume "mycifspv" : mount command failed, status: Failure, reason: Error: Error running cmd [cmd=/usr/bin/mount -t cifs -o uid=333,gid=333,rw,username=myuser
,password=mypassword
,domain=domain.fr //myshare.domain.fr/storage/REC /var/lib/kubelet/pods/f530c0ee-d907-4d47-8532-fb365253d3f3/volumes/juliohm~cifs/mycifspv] [response=mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
]: exit status 32
  Warning  FailedMount  90s (x8 over 22m)  kubelet, ******.domain.fr  Unable to attach or mount volumes: unmounted volumes=[test], unattached volumes=[test default-token-lm9nf]: timed out waiting for the condition_

It seems there is a case return after login and password in the mount command. I check my secret and there is no case return when i decode my login/password.

When I use same secret/pv/pvc/deployement with version 0.6, all is working fine.

Thanks,

**Comment by halkeye** [comment]
When you declare your base64 of your secret, is there a new line in the base64?

**Comment by juliohm1978** [comment]
@halkeye's tip is a good start.

https://kubernetes.io/docs/concepts/configuration/secret/

The Secret's data might have been created with a trailing new line character. It's a common mistake when using shell tools like `echo` and `base64`.

```
> echo hello | base64
aGVsbG8K

> echo -n hello | base64
aGVsbG8=
```

The `-n` flag tells echo to not include a new line character at the end of the string.

**Comment by halkeye** [comment]
I personally love https://github.com/lbolla/kube-secret-editor

**Comment by juliohm1978** [comment]
@Leopol35,

Can you, please, test `juliohm/kubernetes-cifs-volumedriver-installer:2.1-beta`? It includes PR https://github.com/juliohm1978/kubernetes-cifs-volumedriver/pull/22 that was just merged.

This version should trim new line characters and carriage returns from the password before using it.

**Comment by Leopol35** [comment]
Hello,

Thanks both of you for your interests!

@halkeye, this is working using your "echo" with version "2.0" 👍 . For your information, i was using "echo "password" | base64 -w 0"

@juliohm1978 i use 2.1-beta, and it's working with my old credentials, so your fix is working 👍 

Thanks for you help. This is my first issue in github, i close the issue ?

**Comment by juliohm1978** [comment]
That's great. I'll provide a new version release right away.
