### ISSUE TITLE
Kube node fails to chown and chmod the SMB share and then times out

### ISSUE THREAD

**Issue by brec** [juliohm1978/kubernetes-cifs-volumedriver#23]
Hi, thanks for this great project! I appreciate the work that's gone into it.

I'm close to having this working, but ran into an issue that's stumped me and would appreciate any help.

The pod will fail to create, because the mount operation to the pod times out. However, the volume is mounted and present on the worker node, in the correct directory. So it appears that the CIFS mount operation is successful.  Looking on the node's logs, kubernetes attempts to do a chown and chmod on the volume, and is unable to because of a permissions denied. The volume then times out while trying to mount that volume to the pod.

Kubernetes version:
1.15.11-eks

**PV config:**

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
spec:
  storageClassName: none
  capacity:
    storage: 10Gi
  flexVolume:
    driver: juliohm/cifs
    options:
      opts: vers=1.0,uid=616444004,gid=616444004
      server: our-server-name.net
      share: /m
    secretRef:
      name: cifs-secret
  accessModes:
    - ReadWriteMany
```

**PVC Config:**

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
spec:
  resources:
    requests:
      storage: 10Gi
  volumeName: test-volume
  storageClassName: none
  accessModes:
    - ReadWriteMany
```

**Deployment Config:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-test
  template:
    metadata:
      labels:
        app: windows-test
    spec:
      containers:
      - image: internal.container.location
        name: test-kube
        command: ["/bin/sh"]
        args: ["-c", "sleep 500000"]
        volumeMounts:
        - name: test
          mountPath: "/test"
      securityContext:
        runAsUser: 616444004
        runAsGroup: 616444004
      volumes:
      - name: test
        persistentVolumeClaim:
          claimName: test-claim
```

API logs from pod:
`k describe po windows-test-77757d7b67-55rcp`
```bash
  Warning  FailedMount  61s                  kubelet, ip-*-*-*-*.our-host.net  Unable to mount volumes for pod "windows-test-77757d7b67-55rcp_namespace-dev(d325bc7e-8107-4785-a66a-c8fd3ecee7fe)": timeout expired waiting for volumes to attach or mount for pod "namespace-dev"/"windows-test-77757d7b67-55rcp". list of unmounted volumes=[test default-token-ts26q]. list of unattached volumes=[test default-token-ts26q]`
```

These logs and information are from the k8 node where the pod is deployed.

**The mounted PVC info:**
`stat /var/lib/kubelet/pods/9d0782a0-59c0-4c0b-be0e-cedcb1a5cf15/volumes/juliohm~cifs/test-volume`
```base
  File: test-volume
  Size: 16384     	Blocks: 32         IO Block: 16384  directory
Device: b1h/177d	Inode: 1407374883553285  Links: 2
Access: (0755/drwxr-xr-x)  Uid: (616444004/ UNKNOWN)   Gid: (616444004/ UNKNOWN)
Access: 2020-08-18 13:40:57.966982200 +0000
Modify: 2020-08-18 13:40:57.966982200 +0000
Change: 2020-08-18 13:40:57.966982200 +0000
 Birth: -`
```
**journalctl log:**
```bash
Aug 21 16:23:42 ip-*-*-*-*.prd-our.host.net kubelet[4639]: I0821 16:23:42.942002    4639 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "test-volume" (UniqueName: "flexvolume-juliohm/cifs/d325bc7e-8107-4785-a66a-c8fd3ecee7fe-test-volume") pod "windows-test-77757d7b67-55rcp" (UID: "d325bc7e-8107-4785-a66a-c8fd3ecee7fe")
Aug 21 16:23:42 ip-*-*-*-*.prd-our.host.net kubelet[4639]: I0821 16:23:42.942042    4639 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-ts26q" (UniqueName: "kubernetes.io/secret/d325bc7e-8107-4785-a66a-c8fd3ecee7fe-default-token-ts26q") pod "windows-test-77757d7b67-55rcp" (UID: "d325bc7e-8107-4785-a66a-c8fd3ecee7fe")
Aug 21 16:23:43 ip-*-*-*-*.prd-our.host.net kubelet[4639]: E0821 16:23:43.057349    4639 volume_linux.go:73] Chown failed on /var/lib/kubelet/pods/d325bc7e-8107-4785-a66a-c8fd3ecee7fe/volumes/juliohm~cifs/test-volume: chown /var/lib/kubelet/pods/d325bc7e-8107-4785-a66a-c8fd3ecee7fe/volumes/juliohm~cifs/test-volume: permission denied
Aug 21 16:23:43 ip-*-*-*-*.prd-our.host.net kubelet[4639]: E0821 16:23:43.058439    4639 volume_linux.go:88] Chmod failed on /var/lib/kubelet/pods/d325bc7e-8107-4785-a66a-c8fd3ecee7fe/volumes/juliohm~cifs/test-volume: chmod /var/lib/kubelet/pods/d325bc7e-8107-4785-a66a-c8fd3ecee7fe/volumes/juliohm~cifs/test-volume: permission denied
Aug 21 16:25:45 ip-*-*-*-*.prd-our.host.net kubelet[4639]: E0821 16:25:45.872824    4639 kubelet.go:1674] Unable to mount volumes for pod "windows-test-77757d7b67-55rcp_namespace-dev(d325bc7e-8107-4785-a66a-c8fd3ecee7fe)": timeout expired waiting for volumes to attach or mount for pod "namespace-dev"/"windows-test-77757d7b67-55rcp". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-ts26q]; skipping pod
Aug 21 16:25:45 ip-*-*-*-*.prd-our.host.net kubelet[4639]: E0821 16:25:45.872858    4639 pod_workers.go:190] Error syncing pod d325bc7e-8107-4785-a66a-c8fd3ecee7fe ("windows-test-77757d7b67-55rcp_namespace-dev(d325bc7e-8107-4785-a66a-c8fd3ecee7fe)"), skipping: timeout expired waiting for volumes to attach or mount for pod "namespace-dev"/"windows-test-77757d7b67-55rcp". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-ts26q]
```

Thanks for any help!

**Comment by brec** [comment]
Adding some more detail:

Our kubelet user runs as root, so it's surprising that it gets a permission denied.

I've also tried a few different deployment configs for both our deployment and the persistent volume. I've tried using a `securityContext` and supplied a `runAsUser`, `runAsGroup`, and `fsGroup` configurations. These other configurations result in the same permission denied error when the kubelet tries a chown and chmod.

I think the error is coming from this function:
https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/volume/volume_linux.go#L39
If it is, it's surprising that the kubelet still tries to chown or chmod even when the `fsGroup` is not declared.

**Comment by juliohm1978** [comment]
Hey, thanks! I think you are right.

But the error itself might be related to the credentials used (the user/password in your Secret). Is it possible that it might not have enough privileges? Maybe try with a more privileged user?

Either way, that is a really interesting insight. I never realized that `fsGroup` from a pod security policy results in Kubelet actually trying to `chwon/chmod` the entire contents of every volume it mounts. That looks insanely inefficient! I'd say, down right impossible to use with volumes that hold Terabytes or Petabytes of data.

Someone realized that and decided to give FlexVolumes the ability to disable `fsGroup` ownership capability upstream.

https://github.com/kubernetes/kubernetes/commit/6584df59145b948d56704a504b1bef2cf9ced8fc

This makes perfect sense in this case, since we just use the pod's `fsGroup` to mount as a given user. Regardless if your credentials end up working, I will push a new version that disable the `fsGroup` capability for this driver.

**Comment by juliohm1978** [comment]
Can you give `2.2-beta` a try? The image has been pushed.

**Comment by brec** [comment]
Hey @juliohm1978 this is an interesting insight, and explains why it's trying to change the owner, I wasn't sure if that was intended or not. The cifs user / secret user is limited to prevent any unwanted ownership changes. I think using a "super" user is a last option, I would prefer to resolve this by using the new image.

I will try the new image and let you know how it goes.

Thanks again for helping !

**Comment by juliohm1978** [comment]
No problem. I mentioned using a super user just for verification. If it works, then you know the user in your Secret needs more permission. But I do expect 2.2-beta to work with the same credentials you have now.

**Comment by brec** [comment]
@juliohm1978 It's working ! The windows share mounts without issue.  

This is the security context declaration in our deployment that is working:
```yaml
    spec:
      ......
      securityContext:
        runAsUser: ******
        runAsGroup: ******
      volumes:
     ......

```

Thanks again for fixing this.

**Comment by juliohm1978** [comment]
Glad to hear!
2.2 coming up next.

**Comment by juliohm1978** [comment]
v2.2 released, which disables `fsGroup` capability for this driver.

https://github.com/juliohm1978/kubernetes-cifs-volumedriver/releases/tag/v2.2
