### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Nwhouse** [juliohm1978/kubernetes-cifs-volumedriver#24]
Hello.
I have installed the cifs driver on my raspberry pi cluster and I and getting this error.
standard_init_linux.go:211: exec user process caused "exec format error"

Can you advise?

Thanks

**Comment by halkeye** [comment]
That says the binary your trying to run is not compiled for the architecture that your running it in. Ish

I don't think the docker image used to do the install, by default, is compiled for arm

**Comment by juliohm1978** [comment]
Hi, thanks for the issue report.

I was wondering myself when this demand would actually show up. But I'm not quite sure yet how to cross compile to multiple platforms. Would it really just be a matter of setting `GOOS` and `GOARCH` as environment variables? I'm glad to include multiple docker images for different archs, but I need some pointers.

Right how, I guess you'd have to compile the binary yourself, then either create your Docker image or deploy manually.

**Comment by halkeye** [comment]
> Would it really just be a matter of setting GOOS and GOARCH as environment variables?

That would produce the right binary but not the right docker image.

Are you using a ci? I think docker hub can build and tag multiple oses

**Comment by juliohm1978** [comment]
I'm not using any CI right now, but it might be a good time to set things up. Docker Hub automated builds come to mind. I'm open to suggestions.

**Comment by halkeye** [comment]
Docker hub is probably the most straight forward. But apparently it's just a bunch of docker manifest commands so it could be done with any ci or even locally.

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

Until now I only knew it could be done but not how

**Comment by juliohm1978** [comment]
I managed to create several images here by just tweaking `Makefile` and `Dockerfile`.

```
2.3-beta-darwin-amd64
2.3-beta-linux-mips64le
2.3-beta-linux-mips64
2.3-beta-linux-mipsle
2.3-beta-linux-mips
2.3-beta-linux-ppc64le
2.3-beta-linux-ppc64
2.3-beta-linux-arm
2.3-beta-linux-386
2.3-beta-linux-amd64
```
But I have no way of actually testing all of those.

@Nwhouse, can you check if `juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta-linux-arm` works for you?

**Comment by juliohm1978** [comment]
Ok, so I figured out the initial steps with my local copy.

The current 2.3-beta tag is a proper multi-arch image. I can build it with multiple binaries and manifests, but I still can't actually run tests on all of them. I think I can eventually get that working with qemu. Otherwise, I'll start looking for a CI that supports that.

Either way, I can release 2.3 as soon as we get confirmation that it works on arm.

Thanks @halkeye, for the reference!

**Comment by halkeye** [comment]
not Op, but tested with my pi. Looks like the 

```
pi@raspberrypi:~ $ docker run -it --rm juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta-linux-arm
Unable to find image 'juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta-linux-arm' locally
2.3-beta-linux-arm: Pulling from juliohm/kubernetes-cifs-volumedriver-installer
76df9210b28c: Pull complete
5a0e77a487cf: Pull complete
ae4c79cd153d: Pull complete
4c28579aafbc: Pull complete
Digest: sha256:5f9d5a485e941da0d50be10db90a42409026be87012bf90337b5059879d7b184
Status: Downloaded newer image for juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta-linux-arm
standard_init_linux.go:190: exec user process caused "exec format error"
```

```
pi@raspberrypi:~ $ docker run -it --rm juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta-linux-arm sh
standard_init_linux.go:190: exec user process caused "exec format error"
```

```
pi@raspberrypi:~ $ docker run -it --rm juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta-linux-arm /kubernetes-cifs-volumedriver/kubernetes-cifs-volumedriver
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/kubernetes-cifs-volumedriver/kubernetes-cifs-volumedriver\": stat /kubernetes-cifs-volumedriver/kubernetes-cifs-volumedriver: not a directory": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
pi@raspberrypi:~ $ docker run -it --rm juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta-linux-arm /kubernetes-cifs-volumedriver
{"Status":"Failure","Message":"Insufficient arguments","Capabilities":{"Attach":false,"FSGroup":false,"SupportsMetrics":false}}
```

So binary works, container doesn't

**Comment by juliohm1978** [comment]
I see! Busybox should also be arm compatible, and they support that.

Can you try pulling the latest 2.3-beta? I've been pushing that tag multiple times, and it should parent from the correct busybox arch now.

`juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta`

**Comment by halkeye** [comment]
```
pi@raspberrypi:~ $ docker run -it --rm juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta
Installing driver juliohm~cifs/cifs
mkdir: can't create directory '/flexmnt/juliohm~cifs': No such file or directory
```

seems like it'll work

I can't wait to see your final scripts

**Comment by juliohm1978** [comment]
@Nwhouse,
The issue was closed automatically because of my commit comment (fix #24 ...). Please check out `juliohm/kubernetes-cifs-volumedriver-installer:2.3-beta` to make sure it works. This image should provide multiple binaries for each of these initially supported archs:

* linux/amd64
* linux/386
* linux/arm
* linux/arm64
* linux/ppc64le

@halkeye,
The modifications are commited to master. More details on the setup in the documentation, as well. Thanks for the help!

**Comment by Nwhouse** [comment]
@juliohm1978 
Thanks a bunch for this. I am excited to try it.
I am still new to this so if you can provide me the commands to run to perform the install I would be very grateful and I will report back my findings.

Thanks!

**Comment by halkeye** [comment]
https://github.com/juliohm1978/kubernetes-cifs-volumedriver/blob/master/install.yaml#L16

Change the image tag, then re-apply the yaml file

**Comment by Nwhouse** [comment]
Boom!
Worked like a champ.
Thanks a bunch!!!

**Comment by juliohm1978** [comment]
Great!
Also, v2.3 is officially released. You can drop the beta tag and use that for a stable version.
