### ISSUE TITLE
Mount Error - using special characters in password

### ISSUE THREAD

**Issue by jonbrohauge** [juliohm1978/kubernetes-cifs-volumedriver#29]
Due to our password policy, we have to use special characters in all passwords.
The mount command fails when there is a comma in the password.

I have tested using the command line: `mount -t cifs -o username=aUser,password=x!Ya,24 //mount-server/share /target/directory`

However using a credentials-file, the mount works: `mount -t cifs -o $(pwd)/credentials=cifs.credentials //mount-server/share /target/directory`

The credentials `cifs.credentials` file looks like this:
```
username=aUser
password=x!Ya,24
```

Our setup is:
juliohm/kubernetes-cifs-volumedriver-installer:2.3 deployed as a DaemonSet on the cluster.

`kubectl version`

> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

The credentials are base64 encoded in a Secret.

What to do?
Is there any way to convert the secret to a credentials file, or are we forced to go "the relevant authorities" on our knees begging for a "parsable" password?

**Comment by halkeye** [comment]
Apparently you can either encode or quote it. I would guess encode is safer so you dont need to worry about quotes.
https://serverfault.com/questions/170407/how-to-pass-a-password-with-punctuation-characters-to-mount-command

Code should be around https://github.com/juliohm1978/kubernetes-cifs-volumedriver/blob/master/main.go#L147

I remember the credential file was dropped when the rewrite happened to golang. I assume due to not having to worry about leaving a file behind.

**Comment by jonbrohauge** [comment]
I've tried both, and neither works. If I URL encode, I get a permission denied, du to the password is wrong. Quotes are the same issue.
The value of the password is taken very literal. If I encode `x!Ya,24` the value is `x%21Ya%2C24`, and it's still permission denied, due to the access sees the encoded password as wrong. Same thing goes for, if I use quotes. then the password value is seen as this literal string: `"x!Ya,24"` or`'x!Ya,24'`

**Comment by juliohm1978** [comment]
Hi @jonbrohauge. Thanks for the report!

Have you tried encoding with backslashes? Maybe `x!Ya\,24` ?

**Comment by jonbrohauge** [comment]
@juliohm1978 Same, same...

The parameter password expects a literal string, so using backslashes produces an error as well.
I just retried it to be sure 😉

**Comment by juliohm1978** [comment]
Do you have any output of the error message?

I'm trying to understand why this fails by parsing, especially when it is not executed by a shell. We are using the os/exec package, which should feed the contents of the password directly as an argument for the `mount` command, without any shell processing.

**Comment by juliohm1978** [comment]
For example, I would expect this to fail in bash for sure:

```
$ echo x!Ya,24
bash: !Ya,24: event not found
```

But, under Go's os/exec, it works fine.

```
package main

import (
	"fmt"
	"os/exec"
)

func main() {
	var cmd = exec.Command("echo")
	cmd.Args = append(cmd.Args, "x!Ya,24")
	var out,_ = cmd.Output()
	fmt.Printf("%s\n", out)
}
```

**Comment by jonbrohauge** [comment]
Test:
`sudo mount -t cifs //server/share /target/directory/ -o username=aUser,password=4o)yuOxB5i,h`
Result:
> -bash: syntax error near unexpected token `)'

Test without escaped characters:
`sudo mount -t cifs //server/share /target/directory/ -o username=aUser,password='4o)yuOxB5i,h'`
`sudo mount -t cifs //server/share /target/directory/ -o username=aUser,password="4o)yuOxB5i,h"`
Result:
> mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

Test with escaped characters:
`sudo mount -t cifs //server/share /target/directory/ -o username=aUser,password=4o\)yuOxB5i\,h`
`sudo mount -t cifs //server/share /target/directory/ -o username=aUser,password="4o\)yuOxB5i\,h"`
Result:
> mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

AFAICT the paranthesis `)` is apparently escapable, but the comma `,` is not. It kind of makes sense, since the comma `,` is the parameter separator.

**Comment by jonbrohauge** [comment]
I'm testing the mount-command on a Debian Buster 10.8
Using bash-shell: GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

**Comment by juliohm1978** [comment]
Do you have access to a Go runtime? Can you test if this works?

```
package main

import (
	"fmt"
	"os/exec"
)

func main() {
	var cmd = exec.Command("mount")
	cmd.Args = append(cmd.Args, "-t", "cifs", "//server/share", "/target/directory/", "-o", "username=aUser,password=4o)yuOxB5i,h")
	var out,_ = cmd.Output()
	fmt.Printf("%s", out)
}
```

Save the contents to a file `test.go` and run with `sudo go run test.go`

**Comment by jonbrohauge** [comment]
I do not have any go runtime installed currently
Point me in the right direction, and I try you above test.

**Comment by juliohm1978** [comment]
It's quite simple to improvise. Just download a recent Go package (https://golang.org/dl/go1.16.3.linux-amd64.tar.gz). 

Unpack to any directory and include `GO_INSTALL_DIR/bin` to your shell `$PATH`. If not you can just run directly from `GO_INSTALL_DIR/bin/go run test.go`

**Comment by jonbrohauge** [comment]
I get no output...

**Comment by juliohm1978** [comment]
And the mount? Did not work?

**Comment by jonbrohauge** [comment]
I tried your echo-example, which gave me no output as well

EDIT: I made a typo in copy/pasting your example 😳 
The example outputs the expected text

**Comment by juliohm1978** [comment]
Ok.. can you post the error that appears in the pod description?

**Comment by jonbrohauge** [comment]
When I try to mount with credentials where the password does not contain a comma, it works.
And I need to run the go-script as `sudo` due to mount requiring `sudo` to run
I'm redeploying with the credentials "that broke the build". BRB

**Comment by jonbrohauge** [comment]
Warning  FailedMount  14s (x6 over 29s)  kubelet, k8sd04b1  MountVolume.SetUp failed for volume "monitoring-grafana-data" : mount command failed, status: Failure, reason: Error: Error running cmd [cmd=/usr/bin/mount -t cifs -o rw,username=[REDACTED_USERNAME],**password=4o)yuOxB5i,h**,dir_mode=0777,file_mode=0777,noperm //server/share /var/lib/kubelet/pods/2bc8e676-7703-489c-aa17-1813432106da/volumes/juliohm~cifs/monitoring-grafana-data] [response=mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
]: exit status 32

If you look closely, the options are parsed as: 
rw,
username=[REDACTED_USERNAME],
password=4o)yuOxB5i,
h,
dir_mode=0777,
file_mode=0777,
noperm

The password is split, due to the comma, but I believe the error message is due to the paranthesis `)` is not escaped

**Comment by jonbrohauge** [comment]
Everywhere I've looked, there is only one answer, use a credentials-file, if you have special characters in your username or password.
Is there any way to take the username/password from the Secret, and generate a temporary file that is used for the mount and then discarded?

**Comment by juliohm1978** [comment]
I think I fully understand the issue now. It's does relate to parsing command line arguments, but all the way down to the level of mount's own implementation. That is a known issue :D

`mount` tries to break the `-o` parameter value using commas. So, it will certainly break your password and think the following `h` is not a valid parameter. There is really no way to escape this character in mount's command line.

There is, however, a `PASSWD` environment variable we should be able to set.

Can you check if this works?

```
PASSWD='4o)yuOxB5i,h' mount -t cifs //server/share /target/directory/ -o username=aUser,password=4o)yuOxB5i,h
```

I might be able to include this as an optional form of reaching the password, but it does require a new release of this driver.

**Comment by jonbrohauge** [comment]
I'll test this, first thing tomorrow morning.

**Comment by jonbrohauge** [comment]
According to this link: https://linux.die.net/man/8/mount.cifs it should work.

**Comment by juliohm1978** [comment]
I managed to cook a 2.4-beta preview that incorporates a new option. Can you test it? Install this version of the driver:

```
juliohm/kubernetes-cifs-volumedriver-installer:2.4-beta
```

And modify your volume to include `passwdMethod: env`. For example:

```yaml
      volumes:
      - name: vol1
        flexVolume:
          driver: juliohm/cifs
          options:
            server: mysamba-server
            share: /myshare
            passwdMethod: env
          secretRef:
            name: client-credentials
```

This should cause the driver to use the `PASSWD` environment variable, instead of the usual `password=***` option. I was able to reproduce the problem and work around it with this new option.

Let me know how it goes.

**Comment by jonbrohauge** [comment]
I've added `passwdMethod: env` to the options, deployed version 2.4-beta and it works.
Thank you for the quick solution.

**Comment by juliohm1978** [comment]
Great!

I'm working on a few other issues I found while testing this one. There should be a fresh 2.4 release soon.
