### ISSUE TITLE
Pod starts successfully but volume is not mounted

### ISSUE THREAD

**Issue by timmy59100** [juliohm1978/kubernetes-cifs-volumedriver#34]
Similar to https://github.com/juliohm1978/kubernetes-cifs-volumedriver/issues/31 the pod starts successfully but the volume is not mounted. 

Since this week the volume gets not properly mounted anymore except on one node where it still works.

The logs on the node which the mount works looks the same.

Logs on unsuccessful mount:

volumedriver log: 

`2022/03/15 18:20:38 [mount -t cifs -o rw,username=USERNAME,password=PASSWORD,domain=DOMAIN,rw,file_mode=0770,dir_mode=0770 //IP/apps$/INTERN/PATH /var/lib/kubelet/pods/f7d297ce-e760-4c8b-b8c1-95f9221f8187/volumes/juliohm~cifs/cpe-filestore-test-cifs-aveniq]
2022/03/15 18:20:38 {"Status":"Success","Message":"","Capabilities":{"Attach":false,"FSGroup":false,"SupportsMetrics":false}}`

Kubelet log:

pod: test-lua-67bc9dbb-bnxss
volume: cpe-filestore-test-cifs-aveniq

`I0315 18:10:18.834040    1636 topology_manager.go:187] [topologymanager] Topology Admit Handler
I0315 18:10:18.834279    1636 reflector.go:219] Starting reflector *v1.Secret (0s) from object-"filenet-test-aveniq"/"default-token-lzrhb"
I0315 18:10:18.953339    1636 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-lzrhb" (UniqueName: "kubernetes.io/secret/a6a501da-c043-4ca7-b007-645b5bfa4cc3-default-token-lzrhb") pod "test-lua-67bc9dbb-bnxss" (UID: "a6a501da-c043-4ca7-b007-645b5bfa4cc3")
I0315 18:10:18.953629    1636 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "cpe-filestore-test-cifs-aveniq" (UniqueName: "juliohm/cifs/a6a501da-c043-4ca7-b007-645b5bfa4cc3-cpe-filestore-test-cifs-aveniq") pod "test-lua-67bc9dbb-bnxss" (UID: "a6a501da-c043-4ca7-b007-645b5bfa4cc3")
I0315 18:10:19.054711    1636 reconciler.go:269] operationExecutor.MountVolume started for volume "default-token-lzrhb" (UniqueName: "kubernetes.io/secret/a6a501da-c043-4ca7-b007-645b5bfa4cc3-default-token-lzrhb") pod "test-lua-67bc9dbb-bnxss" (UID: "a6a501da-c043-4ca7-b007-645b5bfa4cc3")
I0315 18:10:19.054893    1636 reconciler.go:269] operationExecutor.MountVolume started for volume "cpe-filestore-test-cifs-aveniq" (UniqueName: "juliohm/cifs/a6a501da-c043-4ca7-b007-645b5bfa4cc3-cpe-filestore-test-cifs-aveniq") pod "test-lua-67bc9dbb-bnxss" (UID: "a6a501da-c043-4ca7-b007-645b5bfa4cc3")
I0315 18:10:19.061873    1636 operation_generator.go:672] MountVolume.SetUp succeeded for volume "default-token-lzrhb" (UniqueName: "kubernetes.io/secret/a6a501da-c043-4ca7-b007-645b5bfa4cc3-default-token-lzrhb") pod "test-lua-67bc9dbb-bnxss" (UID: "a6a501da-c043-4ca7-b007-645b5bfa4cc3")
I0315 18:10:19.068028    1636 util.go:53] found flex volume secret info: password
I0315 18:10:19.068079    1636 util.go:53] found flex volume secret info: username
I0315 18:10:19.128141    1636 operation_generator.go:672] MountVolume.SetUp succeeded for volume "cpe-filestore-test-cifs-aveniq" (UniqueName: "juliohm/cifs/a6a501da-c043-4ca7-b007-645b5bfa4cc3-cpe-filestore-test-cifs-aveniq") pod "test-lua-67bc9dbb-bnxss" (UID: "a6a501da-c043-4ca7-b007-645b5bfa4cc3")
I0315 18:10:19.202057    1636 kuberuntime_manager.go:439] No sandbox for pod "test-lua-67bc9dbb-bnxss_filenet-test-aveniq(a6a501da-c043-4ca7-b007-645b5bfa4cc3)" can be found. Need to start a new one
I0315 18:10:20.229464    1636 kubelet.go:1952] SyncLoop (PLEG): "test-lua-67bc9dbb-bnxss_filenet-test-aveniq(a6a501da-c043-4ca7-b007-645b5bfa4cc3)", event: &pleg.PodLifecycleEvent{ID:"a6a501da-c043-4ca7-b007-645b5bfa4cc3", Type:"ContainerDied", Data:"1de2392587bafbf31b94054664ca3f0766382afeba69434736d8bb474b0e41cc"}
W0315 18:10:20.229686    1636 pod_container_deletor.go:79] Container "1de2392587bafbf31b94054664ca3f0766382afeba69434736d8bb474b0e41cc" not found in pod's containers
I0315 18:10:20.541568    1636 kubelet.go:1921] SyncLoop (UPDATE, "api"): "test-lua-67bc9dbb-bnxss_filenet-test-aveniq(a6a501da-c043-4ca7-b007-645b5bfa4cc3)"
I0315 18:10:21.730305    1636 kubelet.go:1952] SyncLoop (PLEG): "test-lua-67bc9dbb-bnxss_filenet-test-aveniq(a6a501da-c043-4ca7-b007-645b5bfa4cc3)", event: &pleg.PodLifecycleEvent{ID:"a6a501da-c043-4ca7-b007-645b5bfa4cc3", Type:"ContainerStarted", Data:"1de2392587bafbf31b94054664ca3f0766382afeba69434736d8bb474b0e41cc"}
I0315 18:10:22.840925    1636 kubelet.go:1952] SyncLoop (PLEG): "test-lua-67bc9dbb-bnxss_filenet-test-aveniq(a6a501da-c043-4ca7-b007-645b5bfa4cc3)", event: &pleg.PodLifecycleEvent{ID:"a6a501da-c043-4ca7-b007-645b5bfa4cc3", Type:"ContainerStarted", Data:"5ef659b84c1baf52f889320f923500fca42502b424f9e864795306bbb0ddf900"}`

Any help appreciated!

**Comment by timmy59100** [comment]
It was an authentication issue with the share, but it's confusing that the driver says status success.

**Comment by juliohm1978** [comment]
Hi @timmy59100 
My apologies for the late response. Most likely, it's an error situation the driver is not handling well. I'm sorry for not being able to provide further support for this project. I'm certain there are other drivers out there that meet the requirements for the new volume CSI specification, but I can't say I have tested any of them.

Thank you for the issue report, but since I am no longer supporting this repo, I will close the issue. The repo will be archived in the near future.

Best regards.
