### ISSUE TITLE
[Question]: Since flexVolume is deprecated as of kubernetes v1.23, are there any plans to support a CSI driver?

### ISSUE THREAD

**Issue by jonbrohauge** [juliohm1978/kubernetes-cifs-volumedriver#36]
At some point flexVolume will disappear from availability, and since this is the best cifs.mount tool we have found for our kubernetes cluster, I was just wondering, if there are any plans to support a CSI driver as proposed by the docs, or do we need to got hunting again?

https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume

![image](https://github.com/juliohm1978/kubernetes-cifs-volumedriver/assets/9496731/b157d1cb-617d-45fd-9ac0-60ee3bea3fbd)

**Comment by juliohm1978** [comment]
Hi Jon.

I would very much like to continue this project, but I have no time, personally, to keep it going. I don't have any plans to maintain this repo, I haven't had the chance to do that for quite some time. Please do not depend on new versions of this project. Feel free to find the best alternatives.

It's been a pleasure to provide this code to the community. Thank you all so much for the help.
