### ISSUE TITLE
many kubelet issues when pod deleted

### ISSUE THREAD

**Issue by JannikZed** [juliohm1978/kubernetes-cifs-volumedriver#5]
I have a lot of issues with your volume driver .. unfortunately it's mostly impossible right now to delete pods/ they will always stay in status "removing" - the kubelet is showing many errors like:
```
pod "72d79bed-0513-11e9-8c02-96000013XXX" found, but error stat /var/lib/kubelet/pods/72d79bed-0513-11e9-8c02-96000013XXXX/volumes/juliohm~cifs/elasticsearch-snapshot: permission denied occurred during checking mounted volumes from disk
```
and 
```
pod "21db23d1-ed7e-11e8-88cc-960000135XXX" found, but error stat /var/lib/kubelet/pods/21db23d1-ed7e-11e8-88cc-960000135XXX/volumes/kubernetes.io~glusterfs/pvc-d8d36981-ec0a-11e8-9646-960000139e27: transport endpoint is not connected occurred during checking mounted volumes from disk
```

Do you have any clue, what we are doing wrong?

**Comment by juliohm1978** [comment]
I get the feeling. Some of these error messages are really hard to diagnose.

Keep in mind that the driver itself is rather a simple wrapper script to standard mount/umount command lines, and in your case it seems that something else interfering with the kubelet's ability to mount/umount those shares.

My first guess would be to try and mount the remote samba shares yourself. Inside one of your k8s worker nodes, try to `mount -t cifs ...` yourself to any temporary location. Leave the mount point alone for a period of time similar to what your pods start stumbling into errors, and make sure you can still access its contents. If you're lucky you'll run into the issues that kubelet's having and you might get a glimpse into a more meaningful error message.
